[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-e __start -static -nostartfiles"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

# Since we are compiling for a custom target, we can’t use the precompiled version of alloc that is shipped
# with the Rust installation. Instead, we have to tell cargo to recompile the crate from source.
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-rust_os.json"
